[package]
name = "disasm-func"
version = "0.1.0"
authors = ["Jeff Muizelaar <jrmuizel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capstone = "0.8.0"
object = "0.16.0"
cpp_demangle = "0.3.2"
addr2line = "0.15.1"
locate-dwarf = "0.1.0"
gimli = "0.26.1"
symbolic-debuginfo = "8.5.0"
